server:
  port: ${PORT:8761}

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: ${EUREKA_HOST:ms-eureka.up.railway.app}
    prefer-ip-address: false
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    renewal-percent-threshold: 0.90

management:
  endpoints:
    web:
      exposure:
        include: '*'
  port: ${PORT:8761}
