## server:
## port: 8761

## Eureka Server Configuration
## eureka:
## client:
##  registerWithEureka: false
##  fetchRegistry: false
## instance:
##  hostname: ${EUREKA_HOST:localhost}
## server:
##  renewal-percent-threshold: 0.90





server:
  port: ${PORT:8761}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    hostname: ${RAILWAY_PUBLIC_DOMAIN:ms-eureka.up.railway.app}  # URL pública de Eureka
    instance-id: ${spring.application.name}:${random.value}        # único por contenedor
